#!/usr/bin/env python3
"""Builds Spanish translation files (.po + .l10n.php, loaded natively by WordPress 6.5+)
from tools/i18n/*-es.json. Usage: python3 tools/make-translations.py"""
import json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
TARGETS = [
    ('theme-es.json', 'corcovado-foundation', 'wp-content/themes/corcovado-foundation/languages', 'es_ES'),
    ('plugin-es.json', 'corcovado-foundation-core', 'wp-content/plugins/corcovado-foundation-core/languages', 'corcovado-foundation-core-es_ES'),
]

def php_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"

def po_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'

for src, domain, out_dir, base in TARGETS:
    path = os.path.join(ROOT, 'tools/i18n', src)
    if not os.path.exists(path):
        continue
    data = json.load(open(path, encoding='utf-8'))
    os.makedirs(os.path.join(ROOT, out_dir), exist_ok=True)
    with open(os.path.join(ROOT, out_dir, base + '.l10n.php'), 'w', encoding='utf-8') as fh:
        fh.write("<?php\n// Generated by tools/make-translations.py — do not edit by hand.\nreturn ['domain'=>" + php_str(domain) +
                 ",'plural-forms'=>'nplurals=2; plural=n != 1;','language'=>'es_ES','messages'=>[")
        fh.write(','.join(php_str(k) + '=>' + php_str(v) for k, v in data.items()))
        fh.write(']];\n')
    with open(os.path.join(ROOT, out_dir, base + '.po'), 'w', encoding='utf-8') as fh:
        fh.write('msgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n"Language: es_ES\\n"\n"Plural-Forms: nplurals=2; plural=n != 1;\\n"\n"X-Domain: %s\\n"\n\n' % domain)
        for k, v in data.items():
            fh.write('msgid %s\nmsgstr %s\n\n' % (po_str(k), po_str(v)))
    print(domain, len(data), 'strings')
